=== sddhrthrt/ITA/xml-assign/part2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="test.namespace">
    <xs:element name="concerts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ad" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="genre" type="xs:string" />
                            <xs:element name="performer_info" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="first_name" type="xs:string" />
                                        <xs:element name="last_name" type="xs:string" />
                                        <xs:element name="role_in_band" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="performance" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="venue" type="xs:string" />
                                        <xs:element name="address" type="xs:string" />
                                        <xs:element name="contact_number" type="xs:positiveInteger" />
                                        <xs:element name="date" type="xs:date" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="ticket_class" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="class" type="xs:string" />
                                        <xs:element name="cost" type="xs:positiveInteger" />
                                        <xs:element name="discount">
                                            <xs:complexType>
                                                <xs:choice> 
                                                    <xs:element name="Yes" type="xs:string" />
                                                    <xs:element name="No" type="xs:string" />
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="seller_info">
                                        <xs:attribute name="name" type="xs:string" />
                                        <xs:attribute name="email" type="xs:string" />
                                        <xs:attribute name="phone" type="xs:positiveInteger" />
                                        <xs:attribute name="address" type="xs:string" />
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sddhrthrt/ITA/xml-assign/index.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--<?xml-stylesheet type="text/css" href="style-xml.css"?>-->
<?xml-stylesheet type="text/xsl" href="index.xsl"?>
<concerts 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="part2.xsd"
        >
    <ad>
        <name> Swarathma</name>
        <genre> Folk </genre>
        <performer_info>
            <first_name> Siddhartha </first_name>
            <last_name> Thota </last_name>
            <role_in_band> Percussion </role_in_band>
        </performer_info>
        <performer_info>
            <first_name> The </first_name>
            <last_name> Man </last_name>
            <role_in_band> Trumpet </role_in_band>
        </performer_info>
        <performer_info> 
            <first_name> Lazy </first_name>
            <last_name> Duck </last_name>
            <role_in_band> Lead Guitarist </role_in_band>
        </performer_info>
        <performance> 
            <venue> Mangalore </venue>
            <email> org1@mang.com </email>
            <phone> 2938234234 </phone>
            <address> Baikampady, Mangalore </address>
        </performance>
        <performance> 
            <venue> Puttur </venue>
            <email> org2@mang.com </email>
            <phone> 2938429384928 </phone>
            <address> New Jersey, near road side, Puttur </address>
        </performance>
        <ticket_class> 
            <class> Gold </class>
            <cost> 500 </cost>
            <discount> No </discount>
        </ticket_class>
        <ticket_class> 
            <class> Silver </class>
            <cost> 400 </cost>
        </ticket_class>
        <ticket_class> 
            <class> Normal </class>
            <cost> 100 </cost>
        </ticket_class>
        <seller_info> 
            <name> Shah Rukh </name>
            <email> sharukh@porki.com </email>
            <phone> 489238928 </phone>
            <address> Aa maida ill, Bellipady </address>
            <new> </new>
        </seller_info>
    </ad>
    <ad>
        <name> Band Bajaa</name>
        <genre> Instrumental </genre>
        <performer_info>
            <first_name> Harish </first_name>
            <last_name> Tumkur </last_name>
            <role_in_band> Percussion </role_in_band>
        </performer_info>
        <performer_info>
            <first_name> Prem </first_name>
            <last_name> Asgar </last_name>
            <role_in_band> Trumpet </role_in_band>
        </performer_info>
        <performer_info> 
            <first_name> Manesh </first_name>
            <last_name> Hirani </last_name>
            <role_in_band> Lead Guitarist </role_in_band>
        </performer_info>
        <performer_info> 
            <first_name> Hiralal </first_name>
            <last_name> Nandani </last_name>
            <role_in_band> Pianist </role_in_band>
        </performer_info>
        <performance> 
            <venue> Mangalore </venue>
            <email> org1@mang.com </email>
            <phone> 2938234234 </phone>
            <address> Baikampady, Mangalore </address>
        </performance>
        <performance> 
            <venue> Bangalore </venue>
            <email> org2@mang.com </email>
            <phone> 2938429384928 </phone>
            <address> Haranrsipura road, Outer ring road, Industrial area</address>
        </performance>
        <ticket_class> 
            <class> Gold </class>
            <cost> 500 </cost>
            <discount> No </discount>
        </ticket_class>
        <ticket_class> 
            <class> Silver </class>
            <cost> 400 </cost>
            <discount> Yes </discount>
        </ticket_class>
        <ticket_class> 
            <class> Normal </class>
            <cost> 80 </cost>
            <discount> Yes </discount>
        </ticket_class>
        <seller_info> 
            <name> Mada Gowda</name>
            <email> mg@porki.com </email>
            <phone> 489238928 </phone>
            <address> Shurk road, Opp theatre Hall</address>
            <new> </new>
        </seller_info>
    </ad>
    <ad>
        <name> Amima </name>
        <genre> Classical </genre>
        <performer_info>
            <first_name> Shreya </first_name>
            <last_name> Ghoshal </last_name>
            <role_in_band> Vocals </role_in_band>
        </performer_info>
        <performer_info>
            <first_name> Shiva </first_name>
            <last_name> Mani </last_name>
            <role_in_band> Percussion </role_in_band>
        </performer_info>
        <performer_info> 
            <first_name> Mani </first_name>
            <last_name> Dutt </last_name>
            <role_in_band> Lead Guitarist </role_in_band>
        </performer_info>
        <performance> 
            <venue> Pune </venue>
            <email> org1@mang.com </email>
            <phone> 2938234234 </phone>
            <address> Mahanagar Palika Auditorium </address>
        </performance>
        <performance> 
            <venue> Mangalore </venue>
            <email> org2@mang.com </email>
            <phone> 2938429384928 </phone>
            <address> Opp Vidyakendra Temple, Shri gurnatheshwara ashram</address>
        </performance>
        <ticket_class> 
            <class> Gold </class>
            <cost> 500 </cost>
            <discount> Yes  </discount>
        </ticket_class>
        <ticket_class> 
            <class> Silver </class>
            <cost> 400 </cost>
            <discount> No </discount>
        </ticket_class>
        <ticket_class> 
            <class> Normal </class>
            <cost> 80 </cost>
            <discount> No </discount>
        </ticket_class>
        <seller_info> 
            <name> Billi Hira </name>
            <email> sharukh@porki.com </email>
            <phone> 489238928 </phone>
            <address> Opp new mahal road</address>
            <new> </new>
        </seller_info>
    </ad>
    <ad>
        <name> Hee Yaa There</name>
        <genre> Pop </genre>
        <performer_info>
            <first_name> Hish </first_name>
            <last_name> Nich </last_name>
            <role_in_band> Vocal </role_in_band>
        </performer_info>
        <performer_info> 
            <first_name> Taylor </first_name>
            <last_name> Mark </last_name>
            <role_in_band> Percussion </role_in_band>
        </performer_info>
        <performer_info>
            <first_name> The </first_name>
            <last_name> Man </last_name>
            <role_in_band> Trumpet </role_in_band>
        </performer_info>
        <performer_info> 
            <first_name> Brian </first_name>
            <last_name> Samaraveera </last_name>
            <role_in_band> Lead Guitarist </role_in_band>
        </performer_info>
        <performance> 
            <venue> Delhi </venue>
            <email> org1@mang.com </email>
            <phone> 2938234234 </phone>
            <address> Mark weight road, opp Ghanta nagar</address>
        </performance>
        <performance> 
            <venue> Pune</venue>
            <email> org2@mang.com </email>
            <phone> 2938429384928 </phone>
            <address> Beachside Blues, Pune</address>
        </performance>
        <ticket_class> 
            <class> Gold </class>
            <cost> 500 </cost>
            <discount> Yes </discount>
        </ticket_class>
        <ticket_class> 
            <class> Silver </class>
            <cost> 400 </cost>
            <discount> Yes </discount>
        </ticket_class>
        <ticket_class> 
            <class> Normal </class>
            <cost> 100 </cost>
            <discount> No </discount>
        </ticket_class>
        <seller_info> 
            <name> More Piya</name>
            <email> sharukh@porki.com </email>
            <phone> 489238928 </phone>
            <address> Valachil, Pune </address>
            <new> </new>
        </seller_info>
    </ad>
</concerts>
